name: CI
on:
  pull_request:
    branches:
    - main
concurrency: ${{ github.ref }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build -- --env production --output-path testing
      env:
        CSM_STRIPE_KEY: abc
        CSM_CAPTCHA_KEY: abc
